### ISSUE TITLE
do not assume a github account

### ISSUE THREAD

**Issue by dimpase** [alex-konovalov/gap-git-cheat-sheet#1]
The command line to clone assumes that the user has a github account with properly configured ssh access.
However, this might not be the case.
It should be mentioned that cloning via https would always work...

**Comment by alex-konovalov** [comment]
Done in PR #2. Also added the link to [/CONTRIBUTING.md](https://github.com/gap-system/gap/blob/master/CONTRIBUTING.md) to README.md
